### ISSUE TITLE
Intermittently failing back office user test

### ISSUE THREAD

**Issue by irisfaraway** [DEFRA/waste-carriers-back-office#206]
Occasionally we get this failure:

`rspec ./spec/services/user_migration_service_spec.rb:33 # UserMigrationService#sync when there is a backend agency_user who isn't in the back office creates a new back office user`

```
Failures:
  1) UserMigrationService#sync when there is a backend agency_user who isn't in the back office creates a new back office user
     Failure/Error: expect(User.all.count).to eq(number_of_users_before_sync + 1)
     
       expected: 110
            got: 111
     
       (compared using ==)
     # ./spec/services/user_migration_service_spec.rb:36:in 'block (4 levels) in <top (required)>'
```

Cause is unclear, but due to the intermittency it's likely to depend on the order in which the specs are run.
